version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/gstapp
      - PORT=5000
    depends_on:
      - mongo
    networks:
      - gst-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - gst-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - gst-network

  jenkins:
    build: ./jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gst-network
    privileged: true
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock

volumes:
  mongo_data:
  jenkins_home:

networks:
  gst-network:
    driver: bridge